title: Marilyn Croffie
role: Software Engineer & Writer
tagline: Turning tacit technical knowledge into clear systems that last.

theme: minima

author:
  name: Marilyn

collections:
  projects:
    output: true
